Попов Алексей модуль 1 задача 1
lehahel/algo_3sem pull request #1
Opened 2020-09-23 07:46 UTC by lehahel

2020-09-23 07:56 UTC, TalgatMIPT requested changes

2020-09-23 07:56 UTC, TalgatMIPT commented on a/a.cpp
> +    //system("pause");
Закомментированный код

2020-09-23 07:56 UTC, TalgatMIPT commented on a/a.cpp
> +}
Нет пустой строки в конце

2020-09-23 07:56 UTC, TalgatMIPT commented on a/lib.h
> +void calculate_z_function(const string& s, vector<int>& res);
Мы можем вернуть z функцию из метода а не принимать ее аргументом?

2020-09-23 07:56 UTC, TalgatMIPT commented on a/lib.cpp
> +    calculate_z_function(pattern + "#" + text, zfunc);
magic number

2020-09-23 07:56 UTC, TalgatMIPT commented on a/lib.cpp
> +    int n = text.length(), m = pattern.length();
n еще понятно, m - не понятно что такое

2020-09-25 15:55 UTC, TalgatMIPT requested changes

2020-09-25 15:55 UTC, TalgatMIPT commented on a/a.cpp
> +using namespace std;
это плохо

2020-09-25 15:55 UTC, TalgatMIPT commented on a/a.cpp
> +        cout << x << " ";
``` " " ``` - это magic number

2020-09-25 15:55 UTC, TalgatMIPT commented on a/lib.h
> +#pragma once
Давай класс сделаем

2020-09-25 15:55 UTC, TalgatMIPT commented on a/a.cpp
> +    cout << endl;
Для чего этот вывод?

2020-10-12 13:09 UTC, lehahel commented on a/lib.h
> +#pragma once
Нет:(

2020-10-13 13:42 UTC, TalgatMIPT requested changes

2020-10-13 13:42 UTC, TalgatMIPT commented on a/lib.h
> +const std::string space_symbol = " ";
Нет пустой строки в конце файла

2020-10-13 13:42 UTC, TalgatMIPT commented on a/lib.h
> +const std::string union_symbol = "#";
давай такие константы будет с капсом писать

2020-10-13 13:42 UTC, TalgatMIPT commented on a/lib.h
> +std::shared_ptr<std::vector<int>> calculate_z_function(const std::string& s);
Давай сделаем класс

2020-10-13 13:42 UTC, TalgatMIPT commented on a/lib.h
>  #include <vector>
Еще мне не очень нравится нейминг файлов. Что такое lib.h/cpp. Это же не библиотека подключаемая. Можно что-то типа ```substring_finder```

2020-10-15 17:57 UTC, lehahel commented on a/lib.h
> +std::shared_ptr<std::vector<int>> calculate_z_function(const std::string& s);
Ну неть(((

2020-10-28 09:44 UTC, merged